Repository hyomee2/cooking-doraemon, pull requests merged in 2024-08, with the labels that each got.

#1 feat: 마트, 냉장고 기능 개발
  src/main/java/com/cooking_doraemon/aggregate/User.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
Labels: enhancement

#2 feat: recipe 기능 구현
  src/main/java/com/cooking_doraemon/aggregate/Recipe.java
  src/main/java/com/cooking_doraemon/repository/RecipeRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
Labels: enhancement

#3 feat: recipe 기능 추가
  src/main/java/com/cooking_doraemon/db/recipeDB.dat
  src/main/java/com/cooking_doraemon/service/RecipeService.java
Labels: enhancement

#4 feat: user 기능 개발
  src/main/java/com/cooking_doraemon/aggregate/CookingLevel.java
  src/main/java/com/cooking_doraemon/aggregate/User.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/UserService.java
Labels: enhancement

#5 refactor: 마트, 냉장고 기능 리펙토링
  src/main/java/com/cooking_doraemon/repository/RefrigeratorRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
Labels: enhancement

#7 fix: 내 프로필 보기 기능 수정
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/UserService.java
Labels: bug, enhancement

#6 feat: 요리하기 기능 구현
  src/main/java/com/cooking_doraemon/aggregate/Ingredient.java
  src/main/java/com/cooking_doraemon/repository/RecipeRepository.java
  src/main/java/com/cooking_doraemon/repository/RefrigeratorRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/CookingService.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
Labels: enhancement

#8 feat: 냉장고 정리하기 기능 구현
  src/main/java/com/cooking_doraemon/repository/RefrigeratorRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
Labels: enhancement

#9 feat: 레시피 추가 기능 구현
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
Labels: enhancement

#13 refactor: 의존성 주입 수정
  src/main/java/com/cooking_doraemon/aggregate/User.java
  src/main/java/com/cooking_doraemon/repository/MartRepository.java
  src/main/java/com/cooking_doraemon/repository/RecipeRepository.java
  src/main/java/com/cooking_doraemon/repository/RefrigeratorRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/CookingService.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
Labels: refactor

#14 refactor: 리펙터링
  src/main/java/com/cooking_doraemon/repository/MartRepository.java
  src/main/java/com/cooking_doraemon/repository/RecipeRepository.java
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/CookingService.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
  src/main/java/com/cooking_doraemon/service/RefrigeratorService.java
  src/main/java/com/cooking_doraemon/service/UserService.java
Labels: refactor

#15 feat: 레시피 추가 시 존재하는 재료만 입력하는 필터 기능 추가
  src/main/java/com/cooking_doraemon/run/Application.java
  src/main/java/com/cooking_doraemon/service/MartService.java
  src/main/java/com/cooking_doraemon/service/RecipeService.java
Labels: enhancement
